### ISSUE TITLE
Calculation of the success rate

### ISSUE THREAD

**Issue by artpli** [yufeiwang63/RL-VLM-F#3]
Hi Yufei,

Thanks for open-sourcing the codebase!
I noticed that the environments used during evaluation are all the same, so a policy model will either succeed or fail in all of them. As a result, the success rate ends up being either 0% or 100% every time.
Could you please elaborate more on the calculation process? Thank you very much!

Best,
Peng

**Comment by yufeiwang63** [comment]
Hi,

Thanks for your interest in our project.
For the meta-world & cloth folding tasks, the environments are with a fixed initial state. This is because we tried to simplify the tasks in early experiments where we find the baselines frequently fail (even with this fixed initial state, the baselines still fail). As a result, if the policy learning is not stable, the success rate will jump between 0% and 100%.
Although I haven't tested the performance on the RL-VLM-F trained policy/reward on varying initial conditions, I guess it can be robust to small variations in these environments. 
You can modify the environment initial conditions, e.g., for drawer open, using these lines: https://github.com/yufeiwang63/RL-VLM-F/blob/main/metaworld/envs/mujoco/sawyer_xyz/v2/sawyer_drawer_open_v2.py#L21-L22, which determines the variation of the drawer position in the evaluation. 

For other 3 envs such as RopeFlatten, PassWater and CartPole, there are variations in the evaluation. For RopeFlatten and PassWater there are 1000 variations in init states; for CartPole the initial position of the cart and pole are randomized.

**Comment by artpli** [comment]
Thanks for your prompt and detailed response! 

I'm still confused with the calculation of the success rate in the metaworld tasks. From my understanding, when you fix the initial state, given a trained policy model, the success rate will be 0% or 100%, but won't be any number between them like 85%. 
So I still don't know how to get a success rate curve like the first three subfigures in Figure 4. 

Could you please explain more about how to get a success rate curve like the first three subfigures in Figure 4? Sorry if I misunderstood anything.

**Comment by yufeiwang63** [comment]
Sure! We actually smooth the curve for figure 4 in the paper. I think we took the moving average of the last 10 evaluations when making the plot. Therefore in the plot there can be success rates like 80% with this moving average, and further averaging over 5 seeds might result in a success rate like 85%

**Comment by artpli** [comment]
Oh! Thank you for the further explanation, got it now! ♥
